name: Run MSGOBA Client Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.x
          cache: npm
      
      - name: Install dependencies and test
        run: docker build . --target test --tag msgoba-client:$(date +%s)